[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/verif.html"
  status = 200
  force = true

[[redirects]]
  from = "/verif.html"
  to = "/verif.html"
  status = 200
